// Generated by https://quicktype.io

export interface IData {
  data:     Datum[];
  prizes:   string[];
  currency: string;
}

export interface Datum {
  id:       string;
  question: string;
  answers:  Answer[];
}

export interface Answer {
  letterId:  LetterID;
  value:     string;
  isCorrect: boolean;
}

export enum LetterID {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
}
